name: Publish to NPM

on:
  release:
    types: [created]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 19.0
        uses: actions/setup-node@v3
        with:
          node-version: 19.0
          cache: "yarn"
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Tests
        run: yarn test
      - name: Build
        run: yarn build

  publish-npm:
    name: Publish
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: NPM
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 19.0
        uses: actions/setup-node@v3
        with:
          node-version: 19.0
          cache: "yarn"
          registry-url: https://registry.npmjs.org/
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
